sudo: false
language: node_js
node_js: node
git:
  depth: 5
notifications:
  email: false
script: true
deploy:
  provider: script
  script: ".travis/deploy.sh"
  skip_cleanup: true
  on:
    repo: clippings/cdw
    branch: master
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_9e42c25de7d5_key -iv $encrypted_9e42c25de7d5_iv
  -in .travis/id_rsa.enc -out .travis/id_rsa -d
